#!/usr/bin/env bash
#install your load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5652-webs
    bind *:80
    mode http
    balance roundrobin
    server 5652-web-01 54.221.90.110:80 check
    server 5652-web-02 54.226.122.192:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
