#!/usr/bin/env bash
#  Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
